import json,os
from playwright.sync_api import sync_playwright
os.makedirs('/mnt/data/chatbook-tests',exist_ok=True)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 page=b.new_page(viewport={'width':412,'height':915},device_scale_factor=1)
 errs=[];page.on('pageerror',lambda e:errs.append(str(e)))
 page.route('https://fonts.**/*',lambda r:r.abort())
 page.set_content(open('/mnt/data/챗북_바로실행.html').read(),wait_until='domcontentloaded');page.wait_for_timeout(1000)
 page.screenshot(path='/mnt/data/chatbook-tests/home.png',full_page=True)
 print('home',page.title(),page.locator('.book-card').count(), 'overflow',page.evaluate('document.documentElement.scrollWidth>innerWidth'),errs)
 page.evaluate("CB.go('library')");page.wait_for_timeout(300)
 page.screenshot(path='/mnt/data/chatbook-tests/library.png',full_page=True)
 page.evaluate("CB.read('habit')");page.wait_for_timeout(800)
 print('reader',page.evaluate('({pages:CB.Reader.pages,width:CB.Reader.width,height:CB.Reader.height,info:CB.Reader.info(),scroll:CB.Reader.flow.scrollWidth})'),errs)
 page.screenshot(path='/mnt/data/chatbook-tests/reader.png',full_page=True)
 page.get_by_role('button',name='다음 페이지',exact=True).click();page.wait_for_timeout(450)
 print('reader next',page.locator('#reader-page').inner_text(),page.evaluate("CB.progress('habit')"))
 page.evaluate("CB.go('quiz')");page.wait_for_timeout(400)
 page.screenshot(path='/mnt/data/chatbook-tests/quiz.png',full_page=True)
 page.evaluate("CB.go('settings')");page.wait_for_timeout(300)
 page.screenshot(path='/mnt/data/chatbook-tests/settings.png',full_page=True)
 page.evaluate("CB.go('exports')");page.wait_for_timeout(300)
 page.screenshot(path='/mnt/data/chatbook-tests/exports.png',full_page=True)
 print('errors',errs)
 b.close()
