import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../../public/engine/learning.mjs';
import {readingContext,checkSupplements,flowAlarms,groupChapters} from '../../public/engine/narrative.mjs';
import {availableTasks} from '../../engine/runner.mjs';
const fake=()=>({source:{chunks:['c001','c002','c003'].map(id=>({id}))},checkpoints:{},attempts:{},approval:{owner:'test'}});
const plan=[{id:'chapter-one',title:'입력을 계산으로 잇기',chunkIds:['c001','c002']},{id:'chapter-two',title:'다음 개념',chunkIds:['c003']}];
test('읽기 장은 분석 구간을 누락·중복·재정렬 없이 묶는다',()=>{const j=fake();E.setReadingPlan(j,plan);assert.equal(j.readingPlan.length,2);assert.equal(j.approval,undefined);});
for(const ids of [['c001','c003'],['c002','c001','c003'],['c001','c002','c002','c003']])test('잘못된 구간 묶음 '+ids,()=>assert.throws(()=>E.setReadingPlan(fake(),[{id:'c',title:'x',chunkIds:ids}]),e=>e.code==='READING_PLAN_GAP'));
test('장 제목에 거대한 원고를 넣지 못한다',()=>assert.throws(()=>E.setReadingPlan(fake(),[{id:'x',title:'x'.repeat(1000),chunkIds:['c001','c002','c003']}]),e=>e.code==='INVALID_READING_PLAN'));
test('같은 장 앞부분이 없으면 연속 집필 보류',()=>{const j=fake();E.setReadingPlan(j,plan);assert.throws(()=>readingContext(j,'c002'),e=>e.code==='NARRATIVE_CONTEXT_MISSING');});
test('앞부분 전체 대신 4KB 이내 연결 문맥',()=>{const j=fake();E.setReadingPlan(j,plan);j.checkpoints['c001:beginner']={artifact:{paragraphs:[{text:'가'.repeat(10000)}],glossary:Array.from({length:100},(_,i)=>({term:'용어'+i+'나'.repeat(70)}))}};const c=readingContext(j,'c002');assert.ok(E.bytes(c)<=4000);assert.ok(c.previousTail.length<10000);assert.equal(c.chapterId,'chapter-one');});
test('같은 장은 앞 초고를 기다리되 다른 장은 독립 진행',()=>{const j=fake();E.setReadingPlan(j,plan);for(const c of j.source.chunks)j.checkpoints[c.id+':source']={artifact:{}};assert.deepEqual(availableTasks(j).map(x=>x.chunkId),['c001','c003']);j.checkpoints['c001:beginner']={artifact:{}};assert.ok(availableTasks(j).some(x=>x.chunkId==='c002'));});
test('장 구성 변경은 관련 검수만 해제하고 원문·초고 보존',()=>{const j=fake();E.setReadingPlan(j,plan);for(const c of j.source.chunks)for(const stage of ['source','beginner','review'])j.checkpoints[c.id+':'+stage]={artifact:{}};E.setReadingPlan(j,[{...plan[0],title:'새 흐름'},plan[1]]);assert.equal(j.checkpoints['c001:review'],undefined);assert.ok(j.checkpoints['c003:review']);assert.ok(j.checkpoints['c001:source']);assert.ok(j.checkpoints['c001:beginner']);});
const ext=()=>({id:'extra',kind:'explanation',text:'보강',support:{kind:'external',sources:[{url:'https://docs.python.org/3/',locator:'type conversion',checkedAt:'2026-09-23'}]}});
test('추가 설명의 검토한 출처 메타데이터 허용',()=>assert.doesNotThrow(()=>checkSupplements({paragraphs:[ext()]})));
test('원문처럼 위장한 외부 설명 거부',()=>{const p=ext();p.kind='source';assert.throws(()=>checkSupplements({paragraphs:[p]}),e=>e.code==='SUPPLEMENT_LABEL_REQUIRED');});
test('근거 없이 외부 설명 승인 불가',()=>{const p=ext();p.support.sources=[];assert.throws(()=>checkSupplements({paragraphs:[p]}),e=>e.code==='SUPPLEMENT_SOURCE_REQUIRED');});
test('보강 내용에는 개별 정확성 검토가 필요',()=>assert.throws(()=>checkSupplements({paragraphs:[ext()]},{}),e=>e.code==='SUPPLEMENT_REVIEW_REQUIRED'));
test('미해결 보강과 전체 통과는 모순',()=>assert.throws(()=>checkSupplements({paragraphs:[ext()]},{fidelity:'approved',supplementChecks:[{paragraphId:'extra',status:'hold',explanation:'확인 불가'}]}),e=>e.code==='REVIEW_CONTRADICTION'));
test('기계식 소제목 반복은 경고이지 자동 삭제가 아니다',()=>{const p={paragraphs:[1,2,3].map(i=>({id:'p'+i,text:'핵심 정리: 내용'+i}))};assert.equal(flowAlarms(p).length,1);assert.equal(p.paragraphs.length,3);});
test('장 합치기는 본문 재요약 없이 블록 ID와 퀴즈 연결 유지',()=>{const j=fake();E.setReadingPlan(j,plan);const book={id:'book',_engine:{},chapters:['a','b','c'].map(id=>({blocks:[{id,text:'원문 '+id}],glossary:[{term:'변수'}],summary:[]})),questions:[{chapter:0},{chapter:1},{chapter:2}]};groupChapters(j,book);assert.equal(book.chapters.length,2);assert.deepEqual(book.chapters[0].blocks.map(x=>x.id),['a','b']);assert.deepEqual(book.questions.map(x=>x.chapter),[0,0,1]);assert.equal(book.chapters[0].glossary.length,1);});
