import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
import {engineState,sourceDigest,releaseId,createInfo,writeInfo,verifyRelease,serviceWorker,INFO_PATHS} from '../../scripts/engine-info.mjs';
const project=fileURLToPath(new URL('../../',import.meta.url));
const json=(f,x)=>fs.writeFileSync(f,JSON.stringify(x,null,2));
const read=f=>JSON.parse(fs.readFileSync(f,'utf8'));
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'chatbook-info-test-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'public'),{recursive:true});fs.cpSync(path.join(project,'public/engine'),path.join(root,'public/engine'),{recursive:true});json(path.join(root,'package.json'),{type:'module',version:'1.0.3'});fs.writeFileSync(path.join(root,'public/index.html'),'<html><head></head><body><main>reader</main><noscript>reader</noscript></body></html>');fs.writeFileSync(path.join(root,'public/reader.js'),'window.readerWorks=true;');return root;}
async function manifest(root){const s=await engineState(path.join(root,'public'));const v={app:'chatbook',version:read(path.join(root,'package.json')).version,engineVersion:s.version,sourceDigest:sourceDigest(root),sourceSha:'unavailable',runId:null,builtAt:'2026-09-23T00:00:00.000Z'};v.releaseId=releaseId(v);const e={command:'npm test',status:'passed',exitCode:0,checkedAt:v.builtAt,sourceDigest:v.sourceDigest};return {v,e,info:await createInfo(root,v,e)};}
async function output(root){const x=await manifest(root),dist=path.join(root,'dist');fs.cpSync(path.join(root,'public'),dist,{recursive:true});json(path.join(dist,'version.json'),x.v);writeInfo(dist,x.info);return {...x,dist};}
function changeJSON(root,name,fn){const file=path.join(root,name),x=read(file);fn(x);json(file,x);}
test('release is generated from current executable engine and fresh evidence',async t=>{const root=fixture(t),{info}=await manifest(root);const s=await engineState(path.join(root,'public'));assert.equal(info.engine.version,s.version);assert.deepEqual(info.engine.defaults,s.defaults);assert.equal(info.verification.longVideoEndToEnd.status,'not-tested-by-this-build');assert.equal(info.maintenance.runtimeDependency,false);});
test('next app version is reflected without editing the generated description',async t=>{const root=fixture(t),a=await manifest(root);changeJSON(root,'package.json',x=>x.version='1.0.4');const b=await manifest(root);assert.equal(b.info.app.version,'1.0.4');assert.notEqual(a.info.release.id,b.info.release.id);});
test('next engine version is reflected when implementation and manifests agree',async t=>{const root=fixture(t);const original=(await engineState(path.join(root,'public'))).version;const nums=original.split('.').map(Number);nums[2]++;const next=nums.join('.');const f=path.join(root,'public/engine/learning.mjs');fs.writeFileSync(f,fs.readFileSync(f,'utf8').replace(/export const VERSION = '[^']+';/,`export const VERSION = '${next}';`));for(const n of ['defaults.json','learning-policy.json'])changeJSON(root,'public/engine/'+n,x=>x.version=next);assert.equal((await manifest(root)).info.engine.version,next);});
test('removed stage disappears automatically instead of keeping a stale feature claim',async t=>{const root=fixture(t),s=await engineState(path.join(root,'public'));const remove=s.policy.stages[1];const f=path.join(root,'public/engine/learning.mjs');fs.writeFileSync(f,fs.readFileSync(f,'utf8').replace(`'${remove}',`,''));changeJSON(root,'public/engine/learning-policy.json',x=>x.stages=x.stages.filter(v=>v!==remove));assert.equal((await manifest(root)).info.engine.policy.stages.includes(remove),false);});
test('outdated engine version fails closed',async t=>{const root=fixture(t);changeJSON(root,'public/engine/defaults.json',x=>x.version='0.0.0');await assert.rejects(()=>manifest(root),/mismatch/);});
test('changed policy without its matching manifest fails closed',async t=>{const root=fixture(t);changeJSON(root,'public/engine/learning-policy.json',x=>x.fullBookRewrite=!x.fullBookRewrite);await assert.rejects(()=>manifest(root),/mismatch/);});
test('old successful test evidence from another source cannot certify this build',async t=>{const root=fixture(t),{v,e}=await manifest(root);e.sourceDigest='0'.repeat(64);await assert.rejects(()=>createInfo(root,v,e),/test evidence source/);});
test('failed or absent tests cannot be reported as success',async t=>{const root=fixture(t),{v,e}=await manifest(root);e.status='failed';e.exitCode=1;await assert.rejects(()=>createInfo(root,v,e),/successful test/);});
test('all generated release identities and file hashes agree',async t=>{const root=fixture(t),{dist}=await output(root);assert.equal((await verifyRelease(dist)).status,'passed');});
test('app/info version mismatch blocks release verification',async t=>{const root=fixture(t),{dist}=await output(root);changeJSON(dist,'version.json',x=>x.version='9.9.9');await assert.rejects(()=>verifyRelease(dist),/identity/);});
test('modified reader file after validation is detected',async t=>{const root=fixture(t),{dist}=await output(root);fs.appendFileSync(path.join(dist,'reader.js'),'//modified');await assert.rejects(()=>verifyRelease(dist),/published files/);});
test('missing information blocks publishing but does not modify reader source',async t=>{const root=fixture(t),{dist}=await output(root),before=fs.readFileSync(path.join(dist,'reader.js'),'utf8');fs.unlinkSync(path.join(dist,'engine-info.json'));await assert.rejects(()=>verifyRelease(dist));assert.equal(fs.readFileSync(path.join(dist,'reader.js'),'utf8'),before);});
test('engine/ runner and tests participate in source digest; generated output does not',t=>{const root=fixture(t),a=sourceDigest(root);fs.mkdirSync(path.join(root,'engine'));fs.writeFileSync(path.join(root,'engine/runner.mjs'),'export const x=1;');const b=sourceDigest(root);assert.notEqual(a,b);fs.writeFileSync(path.join(root,'public/engine-info.json'),'old output');assert.equal(sourceDigest(root),b);});
test('public JSON never copies arbitrary environment values',async t=>{const root=fixture(t),old=process.env.CHATBOOK_TEST_SECRET;process.env.CHATBOOK_TEST_SECRET='never-publish-test-secret-123';try{assert.equal(JSON.stringify((await manifest(root)).info).includes(process.env.CHATBOOK_TEST_SECRET),false);}finally{if(old===undefined)delete process.env.CHATBOOK_TEST_SECRET;else process.env.CHATBOOK_TEST_SECRET=old;}});
test('service worker does not intercept or pre-cache any metadata URL',()=>{const handlers={};const context={URL,location:{origin:'https://local'},self:{addEventListener:(n,f)=>handlers[n]=f}};vm.runInNewContext(serviceWorker('a'.repeat(64),['./index.html','./reader.js',...INFO_PATHS.map(p=>'.'+p)]),context);for(const p of INFO_PATHS){let intercepted=false;handlers.fetch({request:{method:'GET',url:'https://local'+p+'?fresh=1'},respondWith:()=>{intercepted=true;}});assert.equal(intercepted,false);}const urls=vm.runInNewContext(serviceWorker('a'.repeat(64),['./index.html','./engine-info.json'])+';URLS',{URL,self:{addEventListener:()=>{}}});assert.equal(urls.includes('./engine-info.json'),false);});
// The new contract deletes only retired GENERATED app caches, not user/download stores.
test('retired app caches are removed while unrelated caches are preserved',async()=>{const handlers={},deleted=[],entries=[];const context={URL,location:{origin:'https://local'},caches:{keys:async()=>['chatbook-offline-old','other-app'],delete:async n=>{deleted.push(n);},open:async()=>({keys:async()=>entries,delete:async()=>{}})},self:{clients:{claim:async()=>{}},addEventListener:(n,f)=>handlers[n]=f}};vm.runInNewContext(serviceWorker('a'.repeat(64),['./reader.js']),context);let work;handlers.activate({waitUntil:p=>work=p});await work;assert.deepEqual(deleted,['chatbook-offline-old']);});
test('metadata failure does not block the current offline reader cache',async()=>{const handlers={};const context={URL,Response,location:{origin:'https://local'},fetch:async()=>{throw Error('offline');},caches:{open:async()=>({match:async()=>new Response('reader available')})},self:{addEventListener:(n,f)=>handlers[n]=f}};vm.runInNewContext(serviceWorker('a'.repeat(64),['./reader.js']),context);let result;handlers.fetch({request:{method:'GET',url:'https://local/reader.js'},respondWith:p=>result=p});assert.equal(await(await result).text(),'reader available');});
test('rollback uses self-contained older release metadata rather than a central mutable registry',async t=>{const root=fixture(t),first=await output(root);const old=path.join(root,'old-dist');fs.renameSync(first.dist,old);changeJSON(root,'package.json',x=>x.version='1.0.4');const second=await output(root);assert.notEqual(first.v.releaseId,second.v.releaseId);assert.equal((await verifyRelease(old)).releaseId,first.v.releaseId);});
